# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
    "github.com/spf13/cobra",
    "github.com/spf13/viper",
    "github.com/fatih/color",
    "github.com/shibukawa/configdir",
    "github.com/Sirupsen/logrus",
    "github.com/pkg/errors",
    "github.com/mattn/go-colorable",
    "github.com/chzyer/readline",
    "gopkg.in/natefinch/npipe.v2",
    "github.com/nbutton23/zxcvbn-go",
    "github.com/stretchr/testify",
    "github.com/tobischo/gokeepasslib",
    "github.com/mitchellh/go-homedir",
    "github.com/untoldwind/scrypt-go",
]

[[constraint]]
    name = "github.com/leanovate/microtools"
    branch = "master"

[[constraint]]
    name = "github.com/leanovate/gopter"
    branch = "master"

[[constraint]]
    name = "golang.org/x/crypto"
    source = "github.com/untoldwind/crypto"
    branch = "master"

[[constraint]]
    name = "github.com/junegunn/fzf"
    source = "github.com/untoldwind/fzf"
    branch = "master"

[[constraint]]
    name =  "github.com/spf13/cobra"
    branch = "master"

[[constraint]]
    name =  "github.com/spf13/viper"
    branch = "master"
